### ISSUE TITLE
Support nnls: The Lawson-Hanson algorithm for non-negative least squares (NNLS)

### ISSUE THREAD

**Issue by jsnel** [glotaran/lmfit-varpro#2]
We need to support as one of the methods to calculate the spectra. In essence NNLS is variable projection with constraints on the amplitudes to be strictly positive. 
TIMP makes use of the implementation in the NNLS R package 
https://cran.r-project.org/web/packages/nnls/index.html
This is just a wrapper for 2 fortran functions:
lawson_hanson_nnls.f
nnnpls.f
[Linda Kaufman](https://scholar.google.nl/citations?user=5ZMeAxoAAAAJ&hl=nl&oi=sra) has written an excellent publication on this as well:
[Solving separable nonlinear least squares problems with multiple data sets](https://www.researchgate.net/profile/Linda_Kaufman3/publication/228465950_Solving_separable_nonlinear_least_squares_problems_with_multiple_data_sets/links/56af835708ae9c1968b4576b.pdf)

**Comment by joernweissenborn** [comment]
What about making lmfit-glotaran, with varpro and nnls as sub packages...
It all should be upstreamed to lmfit anyway at some point.

2017-05-07 23:01 GMT+02:00 Joris Snellenburg <notifications@github.com>:

**Comment by jsnel** [comment]
That is a good idea. Agree. I will file new issues with sub tasks and reference this issue.

**Comment by joernweissenborn** [comment]
Cool, maybe also something @YamiNoKeshin can help us with.

2017-05-10 1:56 GMT+02:00 Joris Snellenburg <notifications@github.com>:

**Comment by joernweissenborn** [comment]
The code is in.

@jsnel We need testcases.
